version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegram_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    command: python bot.py
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
